/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SessionObjectPageObjectPage journey");

        opaTest("Navigate to SessionObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThe.onFilterBar().iExecuteSearch();

            Then.onThe.onTable().iCheckRows();
            When.onThe.onTable().iPressRow(0);

            Then.onTheSessionObjectPage.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheSessionObjectPage.onHeader().iCheckHeaderFacet({ facetId: "Header1" });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header1",
                field: "UserName",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header1",
                field: "UserFullName",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckHeaderFacet({ facetId: "Header2" });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header2",
                field: "PersNumber",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header2",
                field: "EmpFullName",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckHeaderFacet({ facetId: "Header3" });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header3",
                field: "WorkCenterId",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header3",
                field: "WorkCenterText",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckHeaderFacet({ facetId: "Header4" });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header4",
                field: "SessionStartDateTime",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header4",
                field: "WorkStart",
                targetAnnotation: ""
            });
            Then.onTheSessionObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Header4",
                field: "WorkEnd",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSessionObjectPage.iCheckNumberOfSections(2);
            When.onTheSessionObjectPage.iPressSectionIconTabFilterButton("AppNavigation");
            Then.onTheSessionObjectPage.iCheckSection({ section: "AppNavigation" });
            When.onTheSessionObjectPage.iPressSectionIconTabFilterButton("Operations");
            Then.onTheSessionObjectPage.iCheckSection({ section: "Operations" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});